### PR TITLE
Prepare for official review, and some other small changes

### PR DESCRIPTION
**Pull request by jmdaweb**
Hi Ricardo.
In these 10 commits, I have prepared your addon to pass the review made by @josephsl, @nvdaes and others. Specifically, the following changes have been made:

* Changed SCRCAT_CONF to SCRCAT_CONFIG in first try / except block
* Move plugin module to globalPlugins folder, and rename it properly. The subfolder is not required, as there is only
one module.
* Added copyright headers. Removed unicode string for Python 3 compatibility in buildVars.py (author field)
* Fixed english readme. Added spanish documentation and translation.
* Call addonHandler.initTranslation() in the global plugin
* Updated translatable strings format from %s, %s, etc. to {arg0}, {arg1}, etc. I have updated the portuguese translations with these changes too.
* Updated version number to 1.1-dev

If you agree, we can send your addon for review to the international NVDA addons list. It's a very useful addon, and I would like to see it in the community website.

### CODE REVIEW

**Comment by RickLeon** [comment]
Hello Jose,


Greate work! Thank you for your contribution. I will merge your PR and create another release.

If you think it would be useful to add it in the official add-ons website, feel free to request a review. Let's see what the comunity say.

I believe some feature like application/profile dictionaries will be added into NVDA core soon or later. That's why I haven't thought of making it official.

Anyway, thank you again.

**Comment by jmdaweb** [comment]
Hi Ricardo.
You can check the review results here: https://nvda-addons.groups.io/g/nvda-addons/topic/20404590
People like this addon very much, but some tasks need to be done before publishing it on the website:

* Support for Windows 10 UWP apps. See @josephsl message for more details.
* Add a menu entry in NVDA dictionaries submenu, under preferences

Both tasks are a bit complex. Although adding a menu item is relatively easy, the dictionaries menu must be located before. If you need help, I might prepare another pull request for the next week.
Regards.
P.S.: @blindhelp is translating this addon into french. Once the review is passed, this translation could be added.

**Comment by RickLeon** [comment]
Hi José,

I will try to work on it this weekend (sorry folks from Prática II). But I can't promise. If you make code contributions, don't forget to add your name as author. For now, I've maid some research.

Initially I thought of getting the dictionaries menu item by Id, but looking into NVDA's code, I found:
menu_preferences.AppendMenu(wx.ID_ANY,_("Speech &dictionaries"),subMenu_speechDicts)
So I think we shouldn't rely on menu Ids.

We could also try getting the menu by it's position, but it also presentes some problems, since the GUI can change. There's the new NVDA GUI, in the Next versions. Also, depending on Windows version the OCR menu item will be present.
For now on, consider prefsMenu = gui.mainFrame.sysTrayIcon.preferencesMenu.GetMenuItems()
To get the dictionaries submenu:
On the new NVDA GUI
prefsMenu[1]

On win10, old GUI (on Win10 there is the OCR item before dictionaries item):
prefsMenu[12]

Not on Win10, old GUI
prefsMenu[11]

But maybe NVDA core team or another add-on developer will decide to add another item before the dictionaries item, who knows.
In this case it may be better to get the dictionaries menu by text:
[item for item in prefsMenu if item.GetText() == _("Speech &dictionaries")][0]

Also, regarding the interface, I think the users should be allowed to list all application dictionaries created, and add option to remove dictionaries.

As for the app identification, I haven't look too much into it, but the NVDA's code for getting the appName for a profile is the following:
gui.mainFrame.prevFocus or api.getFocusObject()).appModule.appName

It seems to work for some UWP apps, but we should try to collect more corner cases.

About the translation. Yes... All contributions are welcome.

**Comment by jmdaweb** [comment]
Hi Ricardo.

I was thinking on using the position. Addon authors add their menu items
usually at the end, let's imagine that noone will do other things, at
least for now. I'll try to create another pull request for you before
the weekend, but I have a lot of work too.

Once menu item and app identification work, we can send a new release
for review. In my opinion, adding the dictionaries management dialog and
merging with profile dictionaries addon are tasks that can be performed
later.

Regards.

**Comment by RickLeon** [comment]
That's ok I think. If anything, they will certainly warn us.

2018-05-30 16:15 GMT-03:00 José Manuel <notifications@github.com>:

**Pull request merged**
